title: Odessa Lohika's Java Club
email: apletnev@lohika.com
description: >- # this means to ignore newlines until "baseurl:"
    Let's brew some java
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://odessajavaclub.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed