title: Odessa Lohika's Java Club
email: apletnev@lohika.com
description: >- # this means to ignore newlines until "baseurl:"
    Let's brew some java
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://odessajavaclub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: "false"

# excerpts
show_excerpts: "true"
excerpt_separator: <!--more-->

# google_analytics: [Your Google Analytics tracking ID]

pagination:
  enabled: true
  debug: false
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  collection: 'posts'
  per_page: 5
  indexpage: 'index'
  title: ':title - page :num of :max'
  limit: 0
  trail: 
    before: 1 # The number of links before the current page
    after: 1  # The number of links after the current page

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
    - jekyll-feed
    - jekyll-paginate-v2
